CREATE TABLE IF NOT EXISTS page
(
pageID INTEGER PRIMARY KEY AUTOINCREMENT,
pageURL VARCHAR(255) NOT NULL UNIQUE ON CONFLICT IGNORE,
depth INTEGER,
filePath VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS link
(
linkID INTEGER PRIMARY KEY AUTOINCREMENT,
linkURL VARCHAR(255) NOT NULL UNIQUE ON CONFLICT IGNORE,
depth INTEGER,
isVisited BOOLEAN,
isSimilar BOOLEAN
);


CREATE TABLE IF NOT EXISTS class
(
classID INTEGER PRIMARY KEY AUTOINCREMENT,
className VARCHAR(255) NOT NULL UNIQUE ON CONFLICT IGNORE
);
CREATE TABLE IF NOT EXISTS page_contain_class
(
FX_page_pageID INTEGER REFERENCES page(pageID), 
FX_class_classID INTEGER REFERENCES class(classID)
);
CREATE TABLE IF NOT EXISTS page_contain_link
(
FX_page_pageID INTEGER REFERENCES page(pageID),
FX_link_linkID INTEGER REFERENCES link(linkID)
);
CREATE TABLE IF NOT EXISTS class_contain_link
(
FX_class_classID INTEGER REFERENCES class(classID),
FX_link_linkID INTEGER REFERENCES link(linkID)
)
